#! /usr/bin/python3
l1 = [1,2,5,8,9]
l2 = [1,5.6,"hello"]
l1[1] = 100
def raise_exception_msg(message=""):
    
    try:
        del l[2]
        print(l1)
    except NameError:
        print(message)
    finally:
        return(l1) 